apiVersion: v1
kind: Service
metadata:
    labels:
      app: be
    name: be
    namespace: devops-app
    annotations:
      argocd.argoproj.io/sync-wave: "4"
spec:
    allocateLoadBalancerNodePorts: true
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 3000-3000
      port: 3000
    selector:
      app: be
    type: LoadBalancer

---      
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "5"
    labels:
      app: be
    name: be
    namespace: devops-app
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: be
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        annotations:
          kubectl.kubernetes.io/restartedAt: "2023-03-11T09:25:04+08:00"
        creationTimestamp: null
        labels:
          app: be
      spec:
        containers:
        - env:
          - name: MONGODB_URL
            value: mongodb://mongodb-service.devops-app.svc.cluster.local
          image: mhntech7/devops-backend:latest
          imagePullPolicy: Always
          name: devops-backend
          ports:
          - containerPort: 3000
            protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
