apiVersion: v1
kind: Service
metadata:
    labels:
      app: fe
    name: fe
    namespace: devops-app
    annotations:
      argocd.argoproj.io/sync-wave: "6"
spec:
    allocateLoadBalancerNodePorts: true
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: 8081-80
      port: 8081
      targetPort: 80
    selector:
      app: fe
    type: LoadBalancer

---       
apiVersion: apps/v1
kind: Deployment
metadata:
    annotations:
      argocd.argoproj.io/sync-wave: "7"
    labels:
      app: fe
    name: fe
    namespace: devops-app
spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        app: fe
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: fe
      spec:
        containers:
        - image: mhntech7/devops-front:latest
          imagePullPolicy: Always
          name: devops-front
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        terminationGracePeriodSeconds: 30
